export const GAME_RULES = {
  MIN_WORD_LENGTH: 4,
  MIELEGRAMMA_BONUS: 7,
  REQUIRED_LETTERS_COUNT: 7,
  MIN_TARGET_WORDS_COUNT: 15,
  MIN_MIELEGRAMMI_COUNT: 1,
  MAX_GENERATION_ATTEMPTS: 500,
} as const;